core_poi:
    resource: "@CoreBundle/Resources/config/routing/poi.yml"
    prefix:   /poi

core_convert:
    path:     /convert/json/to/sql
    defaults: { _controller: CoreBundle:Default:index }

core_course:
      resource: "@CoreBundle/Resources/config/routing/course.yml"
      prefix:   /course

core_home:
      defaults: { _controller: CoreBundle:Default:home }