poi_index:
    path:     /
    defaults: { _controller: "CoreBundle:Poi:index" }
    methods:  GET

poi_show:
    path:     /{id}/show
    defaults: { _controller: "CoreBundle:Poi:show" }
    methods:  GET

poi_ajax:
    path:     /ajax/{id}
    defaults: { _controller: "CoreBundle:Poi:ajax"}
    methods: GET